### ISSUE TITLE
Error installing Prosis Pro on Desktop for a member

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERA#266]
Hi Sagar,
I emailed this to you but also wanted to post it. I am trying to get this member on web but currently they use the desktop on tablets.
any idea for help would be great!

Karen

![windows 11](https://github.com/stellaballa/AERA/assets/26387044/4873d5d2-37cd-446f-a57b-9aa073062852)
![error](https://github.com/stellaballa/AERA/assets/26387044/051b717a-4d29-4434-add9-c5176c94ece4)

We are working with spring garden repair.  They purchased two new laptops and both are running into the same issue.  

We downloaded and installed Prosis Pro.  Followed all the prompts.  Reboot and we get the following errors (see below).  I have also added windows version.  Thank you.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at ProsisPro.Activation.SetSettings() in E:\hardik\project\AERADESKTOP\ProsisPro\Activation.cs:line 137
   at ProsisPro.Activation.timerformload_Tick(Object sender, EventArgs e) in E:\hardik\project\AERADESKTOP\ProsisPro\Activation.cs:line 92
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ProsisPro
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/PROSIS_PRO/ProsisPro.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9172.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
BusinessLayer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/PROSIS_PRO/BusinessLayer.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

 

Tim Worrell, M.S.
717-280-8899

**Comment by SagarPC** [comment]
@kbt1 

Can you please ask user to follow below step and share feedback? 

1) Uninstall previous installation. Please see the below file for the list of software they have to uninstall.
[1.3 Uninstall Instruction.txt](https://github.com/stellaballa/AERA/files/12662649/1.3.Uninstall.Instruction.txt)

2. Re-Install setup but at this time run the setup file as administrator.
![unnamed](https://github.com/stellaballa/AERA/assets/31076567/65104f2e-210a-4e72-8c08-8ada09f193c9)

3. Once you are done with the installation, please run software as Administrator first time.

If user still facing an issue then please let us know we need some access of his computer to look access related stuff.

Please let me know if any questions.

**Comment by kbt1** [comment]
thank you, i will share this information and see what happens.
